### ISSUE TITLE
PyPy support

### ISSUE THREAD

**Issue by desbma** [giampaolo/pysendfile#28]
Any plan to support PyPy / PyPy3 ?

With PyPy I get this error:
`ImportError: unable to load extension module '[path removed]/pysendfile-2.0.1-py2.7-linux-x86_64.egg-tmp/sendfile.so': [path removed]/pysendfile-2.0.1-py2.7-linux-x86_64.egg-tmp/sendfile.so: undefined symbol: PyExc_OSError`

And with PyPy3 :
`ImportError: unable to load extension module '[path removed]/pysendfile-2.0.1-py3.2-linux-x86_64.egg/sendfile.pypy3-23.so': [path removed]/pysendfile-2.0.1-py3.2-linux-x86_64.egg/sendfile.pypy3-23.so: undefined symbol: PyModule_GetState`

I'm using PyPy portable installs from [here](https://github.com/squeaky-pl/portable-pypy).

**Comment by giampaolo** [comment]
This definitively makes sense.

**Comment by giampaolo** [comment]
This is why: https://bitbucket.org/pypy/pypy/issues/2450/cant-import-psutil-on-pypy3-missing
