### ISSUE TITLE
Unable to install this on my machine 

### ISSUE THREAD

**Issue by chanduparmar** [giampaolo/pysendfile#36]
pip install pysendfile
Collecting pysendfile
  Using cached https://files.pythonhosted.org/packages/cd/3f/4aa268afd0252f06b3b487c296a066a01ddd4222a46b7a3748599c8fc8c3/pysendfile-2.0.1.tar.gz
Installing collected packages: pysendfile
  Running setup.py install for pysendfile ... error
    Complete output from command c:\users\parmar\appdata\local\programs\python\python37-32\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Parmar\\AppData\\Local\\Temp\\pip-install-l_mhe13k\\pysendfile\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Parmar\AppData\Local\Temp\pip-record-4yk6xzog\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_ext
    building 'sendfile' extension
    creating build
    creating build\temp.win32-3.7
    creating build\temp.win32-3.7\Release
    C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\bin\HostX86\x86\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -Ic:\users\parmar\appdata\local\programs\python\python37-32\include -Ic:\users\parmar\appdata\local\programs\python\python37-32\include "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\ATLMFC\include" "-IC:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.20.27508\include" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\shared" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\um" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\winrt" "-IC:\Program Files (x86)\Windows Kits\10\include\10.0.17763.0\cppwinrt" /Tcsendfilemodule.c /Fobuild\temp.win32-3.7\Release\sendfilemodule.obj
    sendfilemodule.c
    sendfilemodule.c(49): fatal error C1189: #error:  platfom not supported
    error: command 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.20.27508\\bin\\HostX86\\x86\\cl.exe' failed with exit status 2

OS: Windows 10 64bit

**Comment by giampaolo** [comment]
pysendfile is not supported on windows
